import { ConnectivityProtocol, DbDriverCategory, DbDriverDescriptor } from "./types";

const createTemplate = (overrides: Partial<DbDriverDescriptor["defaultTemplate"]>) => ({
  host: "localhost",
  port: 0,
  database: "",
  user: "",
  password: "",
  ...overrides,
});

export const DB_DRIVERS: DbDriverDescriptor[] = [
  {
    id: "postgresql",
    name: "PostgreSQL",
    vendor: "PostgreSQL Global Development Group",
    categories: ["sql"],
    shortDescription: "Мощная транзакционная СУБД для продуктовых событий",
    accentGradient: "from-sky-500/80 to-blue-500/80",
    tags: ["OLTP", "Open Source", "JSONB"],
    defaultTemplate: createTemplate({ port: 5432, database: "analytics", user: "postgres" }),
    connectivity: { protocol: "postgres", status: "available", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 1,
    docsUrl: "https://www.postgresql.org/docs/",
    connectionProperties: [
      {
        id: "postgres_ssl_mode",
        key: "sslmode",
        label: "SSL Mode",
        description: "Режим проверки SSL-соединения",
        type: "enum",
        options: [
          { value: "disable", label: "Disable" },
          { value: "prefer", label: "Prefer" },
          { value: "require", label: "Require" },
          { value: "verify-full", label: "Verify Full" },
        ],
        defaultValue: "prefer",
      },
      {
        id: "postgres_application_name",
        key: "application_name",
        label: "Application Name",
        description: "Логическое имя подключения, попадает в pg_stat_activity",
        type: "string",
        placeholder: "PocketAnalyst",
      },
      {
        id: "postgres_connect_timeout",
        key: "connect_timeout",
        label: "Connect timeout (s)",
        type: "number",
        defaultValue: "15",
        validationRegex: "^\\d+$",
        validationMessage: "Укажите целое число секунд",
      },
    ],
  },
  {
    id: "mysql",
    name: "MySQL",
    vendor: "Oracle",
    categories: ["sql"],
    shortDescription: "Классический выбор для коммерческих данных",
    accentGradient: "from-amber-400/80 to-orange-500/80",
    tags: ["Ecommerce", "OLTP"],
    defaultTemplate: createTemplate({ port: 3306, database: "analytics", user: "root" }),
    connectivity: { protocol: "mysql", status: "available", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 2,
    docsUrl: "https://dev.mysql.com/doc/",
    connectionProperties: [
      {
        id: "mysql_use_ssl",
        key: "useSSL",
        label: "Use SSL",
        type: "boolean",
        defaultValue: "false",
      },
      {
        id: "mysql_character_encoding",
        key: "characterEncoding",
        label: "Character Encoding",
        type: "string",
        defaultValue: "utf8mb4",
      },
      {
        id: "mysql_allow_public_key",
        key: "allowPublicKeyRetrieval",
        label: "Allow public key retrieval",
        description: "Нужно для SHA-256 аутентификации в облаках",
        type: "boolean",
        defaultValue: "true",
      },
    ],
  },
  {
    id: "sqlserver",
    name: "Microsoft SQL Server",
    vendor: "Microsoft",
    categories: ["sql", "cloud"],
    shortDescription: "Enterprise-уровень для аналитики и финансов",
    accentGradient: "from-purple-500/80 to-indigo-500/80",
    tags: ["Enterprise", "OLTP", "OLAP"],
    defaultTemplate: createTemplate({ port: 1433, database: "master", user: "sa" }),
    connectivity: { protocol: "mssql", status: "available", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 3,
    docsUrl: "https://learn.microsoft.com/sql/",
    connectionProperties: [
      {
        id: "mssql_encrypt",
        key: "encrypt",
        label: "Encrypt",
        type: "boolean",
        defaultValue: "true",
      },
      {
        id: "mssql_trust_server_certificate",
        key: "trustServerCertificate",
        label: "Trust server certificate",
        type: "boolean",
        defaultValue: "false",
      },
    ],
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    vendor: "ClickHouse Inc.",
    categories: ["analytic", "newsql"],
    shortDescription: "Колонночная СУБД для событийной аналитики",
    accentGradient: "from-yellow-400/80 to-orange-400/80",
    tags: ["Columnar", "OLAP", "Events"],
    defaultTemplate: createTemplate({ port: 8123, database: "default", user: "default" }),
    connectivity: { protocol: "clickhouse", status: "preview", supportsAgent: false },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: false },
    popularityRank: 4,
    docsUrl: "https://clickhouse.com/docs",
    connectionProperties: [
      {
        id: "clickhouse_secure",
        key: "secure",
        label: "Secure transport",
        type: "boolean",
        defaultValue: "false",
      },
      {
        id: "clickhouse_compression",
        key: "compress",
        label: "Enable compression",
        type: "boolean",
        defaultValue: "true",
      },
      {
        id: "clickhouse_timeout",
        key: "socket_timeout",
        label: "Socket timeout (ms)",
        type: "number",
        defaultValue: "30000",
        validationRegex: "^\\d+$",
        validationMessage: "Укажите значение в миллисекундах",
      },
    ],
  },
  {
    id: "snowflake",
    name: "Snowflake",
    vendor: "Snowflake Inc.",
    categories: ["cloud", "analytic"],
    shortDescription: "Облачный data warehouse с масштабированием",
    accentGradient: "from-cyan-400/70 to-blue-400/70",
    tags: ["Data Warehouse", "Cloud"],
    defaultTemplate: createTemplate({ host: "account.snowflakecomputing.com", user: "ACCOUNT_ADMIN" }),
    connectivity: { protocol: "snowflake", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: false, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 5,
    docsUrl: "https://docs.snowflake.com/",
  },
  {
    id: "bigquery",
    name: "Google BigQuery",
    vendor: "Google",
    categories: ["cloud", "analytic"],
    shortDescription: "Serverless аналитика поверх GCP",
    accentGradient: "from-orange-500/80 to-red-500/80",
    tags: ["Serverless", "SQL", "GCP"],
    defaultTemplate: createTemplate({ host: "bigquery.googleapis.com", database: "project.dataset" }),
    connectivity: { protocol: "bigquery", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: false, proxy: true, schemaDiscovery: true, ingestion: false },
    popularityRank: 6,
    docsUrl: "https://cloud.google.com/bigquery/docs",
  },
  {
    id: "redshift",
    name: "Amazon Redshift",
    vendor: "AWS",
    categories: ["cloud", "analytic"],
    shortDescription: "Классический облачный data warehouse",
    accentGradient: "from-red-500/80 to-rose-500/80",
    tags: ["AWS", "Columnar"],
    defaultTemplate: createTemplate({ port: 5439, user: "awsuser" }),
    connectivity: { protocol: "redshift", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 7,
    docsUrl: "https://docs.aws.amazon.com/redshift/",
  },
  {
    id: "databricks",
    name: "Databricks SQL",
    vendor: "Databricks",
    categories: ["cloud", "analytic"],
    shortDescription: "Lakehouse SQL endpoint на базе Delta",
    accentGradient: "from-slate-600/80 to-slate-400/80",
    tags: ["Lakehouse", "Delta"],
    defaultTemplate: createTemplate({ host: "adb-0000000000000000.0.azuredatabricks.net", user: "token" }),
    connectivity: { protocol: "databricks", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: false, proxy: true, schemaDiscovery: true, ingestion: false },
    popularityRank: 8,
    docsUrl: "https://docs.databricks.com/sql/",
  },
  {
    id: "oracle",
    name: "Oracle Database",
    vendor: "Oracle",
    categories: ["sql", "enterprise" as DbDriverCategory],
    shortDescription: "Масштабируемая СУБД для финансовых систем",
    accentGradient: "from-red-400/80 to-orange-400/80",
    tags: ["Enterprise", "PL/SQL"],
    defaultTemplate: createTemplate({ port: 1521, database: "orcl", user: "system" }),
    connectivity: { protocol: "oracle", status: "coming_soon", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 9,
    docsUrl: "https://docs.oracle.com/en/database/",
  },
  {
    id: "mariadb",
    name: "MariaDB",
    vendor: "MariaDB Foundation",
    categories: ["sql"],
    shortDescription: "Fork MySQL с расширенными возможностями",
    accentGradient: "from-sky-400/80 to-cyan-400/80",
    tags: ["MySQL compatible", "Open Source"],
    defaultTemplate: createTemplate({ port: 3306, database: "analytics", user: "root" }),
    connectivity: { protocol: "mariadb", status: "preview", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 10,
    docsUrl: "https://mariadb.com/kb/en/documentation/",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    vendor: "MongoDB Inc.",
    categories: ["nosql", "cloud"],
    shortDescription: "Документоориентированная база для event payload",
    accentGradient: "from-emerald-500/80 to-lime-500/80",
    tags: ["JSON", "Atlas"],
    defaultTemplate: createTemplate({ host: "cluster0.mongodb.net", user: "analytics" }),
    connectivity: { protocol: "mongodb", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: false },
    popularityRank: 11,
    docsUrl: "https://www.mongodb.com/docs/",
  },
  {
    id: "cassandra",
    name: "Apache Cassandra",
    vendor: "Apache Foundation",
    categories: ["nosql", "stream"],
    shortDescription: "Децентрализованное хранилище с высокой доступностью",
    accentGradient: "from-teal-500/80 to-green-500/80",
    tags: ["Wide-column", "High throughput"],
    defaultTemplate: createTemplate({ port: 9042, user: "cassandra" }),
    connectivity: { protocol: "cassandra", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: false, ingestion: false },
    popularityRank: 12,
    docsUrl: "https://cassandra.apache.org/doc/latest/",
  },
  {
    id: "redis",
    name: "Redis",
    vendor: "Redis Ltd.",
    categories: ["nosql"],
    shortDescription: "In-memory key/value для realtime сигнала",
    accentGradient: "from-red-500/80 to-orange-500/80",
    tags: ["Cache", "Streams"],
    defaultTemplate: createTemplate({ port: 6379, user: "default" }),
    connectivity: { protocol: "redis", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: false, ingestion: false },
    popularityRank: 13,
    docsUrl: "https://redis.io/docs/",
  },
  {
    id: "cockroachdb",
    name: "CockroachDB",
    vendor: "Cockroach Labs",
    categories: ["newsql", "cloud"],
    shortDescription: "Geo-distributed SQL совместимая с PostgreSQL",
    accentGradient: "from-fuchsia-500/80 to-purple-500/80",
    tags: ["Distributed", "Postgres wire"],
    defaultTemplate: createTemplate({ port: 26257, database: "defaultdb", user: "root" }),
    connectivity: { protocol: "cockroach", status: "preview", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 14,
    docsUrl: "https://www.cockroachlabs.com/docs/",
  },
  {
    id: "yugabytedb",
    name: "YugabyteDB",
    vendor: "Yugabyte",
    categories: ["newsql", "cloud"],
    shortDescription: "Postgres-совместимая распределенная база",
    accentGradient: "from-blue-500/80 to-indigo-500/80",
    tags: ["Distributed", "YCQL", "YSQL"],
    defaultTemplate: createTemplate({ port: 5433, database: "yugabyte", user: "yugabyte" }),
    connectivity: { protocol: "yugabytedb", status: "preview", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 15,
    docsUrl: "https://docs.yugabyte.com/",
  },
  {
    id: "tidb",
    name: "TiDB",
    vendor: "PingCAP",
    categories: ["newsql", "cloud"],
    shortDescription: "Hybrid transactional/analytical (HTAP) движок",
    accentGradient: "from-yellow-500/80 to-amber-500/80",
    tags: ["HTAP", "MySQL wire"],
    defaultTemplate: createTemplate({ port: 4000, database: "test", user: "root" }),
    connectivity: { protocol: "tidb", status: "coming_soon", supportsAgent: true },
    features: { ssl: true, ssh: true, proxy: true, schemaDiscovery: true, ingestion: true },
    popularityRank: 16,
    docsUrl: "https://docs.pingcap.com/tidb/stable",
  },
  {
    id: "athena",
    name: "AWS Athena",
    vendor: "AWS",
    categories: ["cloud", "analytic"],
    shortDescription: "SQL поверх S3 без серверов",
    accentGradient: "from-amber-500/80 to-yellow-500/80",
    tags: ["Serverless", "S3"],
    defaultTemplate: createTemplate({ host: "athena.us-east-1.amazonaws.com" }),
    connectivity: { protocol: "athena", status: "coming_soon", supportsAgent: false },
    features: { ssl: true, ssh: false, proxy: true, schemaDiscovery: true, ingestion: false },
    popularityRank: 17,
    docsUrl: "https://docs.aws.amazon.com/athena/",
  },
];

export const DRIVER_MAP = new Map(DB_DRIVERS.map((driver) => [driver.id, driver]));

export const DEFAULT_DRIVER_ID = DB_DRIVERS[0]?.id ?? "postgresql";

export const getDriverById = (id: string) => DRIVER_MAP.get(id) ?? DB_DRIVERS[0];

export const getDriversByCategory = (category: DbDriverCategory) =>
  DB_DRIVERS.filter((driver) => driver.categories.includes(category));

export const SUPPORTED_PROTOCOLS: ConnectivityProtocol[] = ["postgres", "mysql", "mssql"];
