export const DashboardEvent = {
  ACTIVE_CHART_ID: "dashboard:active-chart-id",
  ACTIVE_TAB_ID: "dashboard:active-tab-id",
  ADD_CHART: "dashboard:add-chart",
  APPEND_LOGICAL_QUERY_FIELDS: "dashboard:append-logical-query-fields",
  APPLY_FILTER_EDITOR: "dashboard:apply-filter-editor",
  BI_FILTERS_APPLIED: "dashboard:bi-filters-applied",
  BI_FILTERS_CHANGED: "dashboard:bi-filters-changed",
  BI_PAGE_SCOPE_CHANGED: "dashboard:bi-page-scope-changed",
  CHART_SOURCES_CHANGED: "dashboard:chart-sources-changed",
  CONNECT_TO_CHART: "dashboard:connect-to-chart",
  CREATE_CHART_FROM_TABLE: "dashboard:create-chart-from-table",
  DELETE_NODE: "dashboard:delete-node",
  EDIT_MODE_CHANGED: "dashboard:edit-mode-changed",
  OPEN_AS_SLICER: "dashboard:open-as-slicer",
  OPEN_AS_TABLE: "dashboard:open-as-table",
  OPEN_DB_EXPLORER: "dashboard:open-db-explorer",
  OPEN_FIRST_REPORT_FILTER_EDITOR: "dashboard:open-first-report-filter-editor",
  OPEN_LIBRARY: "dashboard:open-library",
  PANEL_WIDTH_CHANGED: "dashboard:panel-width-changed",
  PROJECT_CHANGED: "dashboard:project-changed",
  RESET_SLICERS: "dashboard:reset-slicers",
  SAVE_PROJECT: "dashboard:save-project",
  SEMANTIC_ARTIFACTS: "dashboard:semantic-artifacts",
  SET_GLOBAL_DATE_RANGE: "dashboard:set-global-date-range",
  SLICER_SYNC: "dashboard:slicer-sync",
  TABLE_CELL_EDIT: "dashboard:table-cell-edit",
  TAB_CHANGED: "dashboard:tab-changed",
  TOGGLE_MINIMAP: "dashboard:toggle-minimap",
  UPDATE_CHART_DATA: "dashboard:update-chart-data",
  UPDATE_SEMANTIC_ARTIFACTS: "dashboard:update-semantic-artifacts",
} as const;

export type DashboardEventName = (typeof DashboardEvent)[keyof typeof DashboardEvent];
